apiVersion: v1
kind: Pod
metadata:
  name: nginx-affinity
spec:
  affinity:
    nodeAffinity:
    # hard rule
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-ease-1c
            - us-east-1d
    # soft rule        
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - roboshop

      - weight: 10
        preference:
          matchExpressions:
          - key: project
            operator: In
            values:
            - amazon      
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80