apiVersion: v1
kind: Pod
metadata:
  name: nginx-anti-affinity
spec:
  affinity:
    nodeAffinity:
    # hard rule
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: NotInIn # anti-affinity
            values:
            - us-east-1d
    # soft rule        
      # preferredDuringSchedulingIgnoredDuringExecution:
      # # Anti affinity
      # - weight: 100
      #   preference:
      #     matchExpressions:
      #     - key: project
      #       operator: NotIn
      #       values:
      #       - roboshop

      # - weight: 10
      #   preference:
      #     matchExpressions:
      #     - key: project
      #       operator: In
      #       values:
      #       - amazon      
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80