apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::966392474288:role/eksctl-roboshop-2-addon-iamserviceaccount-rob-Role1-bIiQXNSFbcqU
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: roboshop-secret-reader
  namespace: roboshop